# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/AdMob'

target 'reactNativeFirebase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeFirebase

  # target 'reactNativeFirebase-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'reactNativeFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNativeFirebase-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeFirebase-tvOS

  target 'reactNativeFirebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
