# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core', '~> 6.2.0'
pod 'Firebase/RemoteConfig', '~> 6.2.0'

target 'tryReactNativeFirebase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tryReactNativeFirebase

  target 'tryReactNativeFirebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tryReactNativeFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tryReactNativeFirebase-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
